/*
 * Artwork catalogue — single source of truth for the home page, artworks grid,
 * artist pages, artwork pages and AR. Artists live in lib/artists.ts.
 *
 * CONTENT TODO: every value starting with "TODO:" is a placeholder and must be
 * replaced with verified information before launch (dimensions, edition,
 * location/collection, long descriptions, artist bio). `stats` are measured
 * from the GLB files — re-run `npm run thumbnails` after swapping a model and
 * paste the printed numbers back in here.
 */

export interface Sculpture {
  slug: string;
  title: string;
  subtitle: string;
  description: string;
  longDescription: string;
  /**
   * Optional 3D model (Draco GLB). Works that have one get "View in the round"
   * and "See it in your space"; paintings, photographs etc. simply omit it.
   */
  modelUrl?: string;
  /** Main image — a photograph, or a render generated by `npm run thumbnails`. */
  thumbnail: string;
  /**
   * Optional USDZ model used by iOS AR Quick Look. Drop a `<slug>.usdz` next to
   * the GLB under /public/sculptures and point this at it to enable AR on iPhone.
   */
  usdzUrl?: string;
  /** Slug of the artist in lib/artists.ts */
  artistSlug: string;
  /** Shown in "Featured works" on the home page. */
  featured: boolean;
  accent: string;
  offsetX: number;
  offsetY: number;
  defaultZoom: number;
  material: string;
  year: string;
  dimensions: string;
  edition: string;
  location: string;
  tags: string[];
  stats: { triangles: number; fileSizeKB: number };
}

export const sculptures: Sculpture[] = [
  {
    slug: "telangana-woman",
    title: "Telangana Woman",
    subtitle: "The iconic muse",
    description:
      "The iconic subject of Vaikuntam's world — a rural woman adorned with vermilion bindi, almond eyes, and traditional jewellery, capturing the dignity and sensuality of Telangana heritage in three dimensions.",
    longDescription:
      "TODO: extended description — context of the piece, technique, exhibition history.",
    modelUrl: "/sculptures/Lady.glb",
    thumbnail: "/thumbnails/telangana-woman.webp",
    artistSlug: "thota-vaikuntam",
    featured: true,
    accent: "#d4a574",
    offsetX: 0,
    offsetY: -0.1,
    defaultZoom: 2.2,
    material: "Patinated bronze",
    year: "2019",
    dimensions: "TODO: H × W × D cm",
    edition: "TODO: e.g. 1 of 8",
    location: "TODO: collection / gallery",
    tags: ["bronze", "portrait", "telangana", "folk"],
    stats: { triangles: 40000, fileSizeKB: 428 },
  },
  {
    slug: "lord-krishna",
    title: "Lord Krishna",
    subtitle: "Celestial grace",
    description:
      "Rooted in the village life that shaped him, Vaikuntam brings celestial grace and folk intimacy together — poise, peace and primary colour meeting bronze.",
    longDescription:
      "TODO: extended description — context of the piece, technique, exhibition history.",
    modelUrl: "/sculptures/LordKrishna.glb",
    thumbnail: "/thumbnails/lord-krishna.webp",
    artistSlug: "thota-vaikuntam",
    featured: true,
    accent: "#e67e22",
    offsetX: 0,
    offsetY: 0,
    defaultZoom: 3,
    material: "Painted bronze",
    year: "2020",
    dimensions: "TODO: H × W × D cm",
    edition: "TODO: e.g. 1 of 8",
    location: "TODO: collection / gallery",
    tags: ["bronze", "mythology", "krishna", "painted"],
    stats: { triangles: 39999, fileSizeKB: 342 },
  },
  {
    slug: "sacred-gaze",
    title: "Sacred Gaze",
    subtitle: "Dravidian dignity",
    description:
      "From Vaikuntam's series of sculptural heads in patinated bronze — almond eyes and ornate adornment, the calm, dignified faces of his Telangana people rendered in the round.",
    longDescription:
      "TODO: extended description — context of the piece, technique, exhibition history.",
    modelUrl: "/sculptures/Pandit.glb",
    thumbnail: "/thumbnails/sacred-gaze.webp",
    artistSlug: "thota-vaikuntam",
    featured: false,
    accent: "#8b6914",
    offsetX: 0,
    offsetY: 0,
    defaultZoom: 2.2,
    material: "Patinated bronze",
    year: "2018",
    dimensions: "TODO: H × W × D cm",
    edition: "TODO: e.g. 1 of 8",
    location: "TODO: collection / gallery",
    tags: ["bronze", "head", "portrait"],
    stats: { triangles: 39999, fileSizeKB: 481 },
  },
  {
    slug: "dancing-shiva",
    title: "Dancing Shiva",
    subtitle: "Nataraja in motion",
    description:
      "The cosmic dancer caught mid-stride — Vaikuntam's Nataraja fuses the rhythm of South Indian temple iconography with his unmistakable folk sensibility, rendered in flowing, gilded bronze.",
    longDescription:
      "TODO: extended description — context of the piece, technique, exhibition history.",
    modelUrl: "/sculptures/DancingShiva.glb",
    thumbnail: "/thumbnails/dancing-shiva.webp",
    artistSlug: "thota-vaikuntam",
    featured: true,
    accent: "#b8860b",
    offsetX: 0,
    offsetY: 0,
    defaultZoom: 2.4,
    material: "Gilded bronze",
    year: "2021",
    dimensions: "TODO: H × W × D cm",
    edition: "TODO: e.g. 1 of 8",
    location: "TODO: collection / gallery",
    tags: ["bronze", "mythology", "nataraja", "dance"],
    stats: { triangles: 70000, fileSizeKB: 713 },
  },
];

export const getSculpture = (slug: string): Sculpture | undefined =>
  sculptures.find((s) => s.slug === slug);

export const getWorksByArtist = (artistSlug: string) =>
  sculptures.filter((s) => s.artistSlug === artistSlug);

export const getFeaturedWorks = () => sculptures.filter((s) => s.featured);

/** True for placeholder copy that still needs real content. */
export const isTodo = (value: string) => value.startsWith("TODO");
